{% set name = "pyvis" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WestHealth/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ff947e224d9825e4b0f3d6710075945c5c8d13bf60aa54e6396c996f34851a3a
  patches:
    - patches/0001-Fixed-tests-to-run-on-CI.patch
    - patches/0002-Fix-version.patch

build:
  skip: true  [py<=36]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - jinja2 >=2.9.6
    - networkx >=1.11
    - ipython >=5.3.0
    - jsonpickle >=1.4.1

test:
  imports:
    - pyvis
    - pyvis.tests
  source_files:
    - pyvis/tests
  requires:
    - numpy >=1.23.1
    - pip
  commands:
    - pip check
    # test_html requires webdriver-manager, which isn't available yet
    - rm pyvis/tests/test_html.py
    - cd pyvis
    - python -m unittest discover tests

about:
  home: https://github.com/WestHealth/pyvis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE_BSD.txt
  summary: "A Python network graph visualization library"
  description: |
    The goal of Pyvis is to build a python based approach
    to constructing and visualizing network graphs in the same space.
  doc_url: https://pyvis.readthedocs.io/
  dev_url: https://github.com/WestHealth/pyvis/

extra:
  recipe-maintainers:
    - ocefpaf
