{% set version = "0.1.8.1.1" %}

package:
  name: pyvis
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyvis/pyvis-{{ version }}.tar.gz
  sha256: 4929b9e1241d8d7d6f457d7a1a409121a28f136537c6eaea6f6b9893d75ad2b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython >=5.3.0
    - jinja2 >=2.9.6
    - networkx >=1.11
    - jsonpickle

test:
  imports:
    - pyvis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WestHealth/pyvis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE_BSD.txt
  summary: A Python network visualization library

extra:
  recipe-maintainers:
    - ocefpaf
