{% set name = "pyvis" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvis-{{ version }}.tar.gz
  sha256: d5662dbb4a1c4d2eb6b727abe50d5bb9caed7b6ad03a356eea0f68787cd6e30d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ipython >=5.3.0
    - jinja2 >=2.9.6
    - jsonpickle >=1.4.1
    - networkx >=1.11

test:
  imports:
    - pyvis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WestHealth/pyvis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE_BSD.txt
  summary: A Python network visualization library

extra:
  recipe-maintainers:
    - ocefpaf
