travis:
  secure:
    BINSTAR_TOKEN: m4qrMthCupsKoQuxJrKC5XeMRPsTFaFrs2E+6pEIdDWlQARx22+JSjuQt+fyedKZ8yX5Ob6nGrFsj/R8h89cmolIKitRQYfPMqQia9nlO/tuy7fU/ZPh6Zfag0CjJKxDLgIDPsdQRKyEkpJpIaaWmj8hV+5zwifk0YuEbCN23W2y6J0VciGNDWjW20Ov3T/tkH0Bh0tsjJxDKEgh9gzpRINfweVJfkwqQJO+wvc8uvZiGwT9Hq63Uw/bTvZc/tcmBuqTzTQzOUJ6s9MCRMq5f1IyiualxG5Q0qzKOlSxmzrSzNsJaG9ES1QDCX+Thm4NG7VvpOic31oPPA6LRhermqXyexPwCsCXwL6lOA7GS3mK1YPplhr6d+k09/fuBOBXBafM2EN3xttVBaxfMJg3S1DHLEj1ATRi6HouRC9DeT6jJbI2J464qw06lRpwn2fgnK0f8DnFy/meWbjk2TBVr9BXZaoSSPird+r/X1sy8ZxVpXueayogA8fEnyQGP8v0TwxavzL1kj/oJs6wm6KBjer44Ki0Jy655AnJdIQSJQO+Zmuh0sttFbvXJBiPgGEepOpegEHtx7TvUxF2PqAQIPp+lnhi4FZv7yy/8MA/63yk+0pBWErj24nzDLsziYwLb1U9do+uzNHlL96KD/o5Y6QuxkNR/RU4/RK0lg31duM=
conda_forge_output_validation: true
bot:
  automerge: true
